name: Logic

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      is-pre-release:
        type: boolean
        required: true
        default: false

jobs:
  play:
    runs-on: ubuntu-latest

    steps:
    
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{(inputs.is-pre-release == 'true') && 'Pre-Releases' || 'Releases'}}
